name: Deploy

on:
    workflow_run:
        workflows: [CI]
        types: [completed]
        branches: [main]

jobs:
    production-deploy:
        name: Deploy to Production
        if: ${{ github.repository == 'NachoToast/MC-Server-Bot' && github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        concurrency: production_environment
        steps:
            - name: Execute remote build process
              uses: appleboy/ssh-action@v1.2.2
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd services_v2/mc-server-bot
                      git reset --hard --quiet
                      git clean -d --force --quiet
                      git pull --quiet
                      docker compose up --build --detach
                      docker container prune --force
                      docker image prune --all --force
